# -*- coding: utf-8 -*-
"""AI Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvnhTwcgs3yR-AgFJJwKy-T_KQdZ24kr
"""

pip install requests python-dotenv

import requests
import os
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Helper function to ask Gemini API
def ask_gemini(prompt: str, model="gemini-1.5-flash"):
    # Correct Gemini API URL
    gemini_api_url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key=AIzaSyB0bOvlslyOMezTAVBmoDnu5c2Hj1xlWC0"

    headers = {
        "Content-Type": "application/json"
    }

    # Prepare the request payload as per Gemini documentation
    data = {
        "contents": [{
            "parts": [{"text": prompt}]
        }]
    }

    # Make the API request
    response = requests.post(gemini_api_url, json=data, headers=headers)

    # Check response status
    if response.status_code == 200:
        print(response.json())
        return response.json().get("contents", [{}])[0].get("parts", [{}])[0].get("text", "No response from AI.")
    else:
        return f"Error: {response.status_code}, Message: {response.text}"




ask_gemini("What is the capital of France?")

import requests

def ask_gemini(prompt: str, model="gemini-1.5-flash"):
    # Correct Gemini API URL with API key
    gemini_api_url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key=AIzaSyB0bOvlslyOMezTAVBmoDnu5c2Hj1xlWC0"

    headers = {
        "Content-Type": "application/json"
    }

    # Prepare the request payload as per Gemini documentation
    data = {
        "contents": [  # Correct structure
            {
                "parts": [{"text": prompt}]
            }
        ]
    }

    # Debug: Print the request payload
    print("Request Payload:", data)

    # Make the API request
    response = requests.post(gemini_api_url, json=data, headers=headers)

    # Debug: Print the raw response
    print("Raw Response:", response.text)

    # Check response status
    if response.status_code == 200:
        parsed_response = response.json()

        # Extract AI response from "candidates"
        try:
            ai_response = parsed_response["candidates"][0]["content"]["parts"][0]["text"]
            return ai_response
        except (KeyError, IndexError):
            return "Error: AI response structure changed or missing."

    else:
        return f"Error: {response.status_code}, Message: {response.text}"

# Test the function
response = ask_gemini("Explain how AI works")
print("AI Response:", response)

# Base AI Agent class
class AI_Agent:
    def __init__(self, name, role, tools, backstory):
        self.name = name
        self.role = role
        self.tools = tools
        self.backstory = backstory

    def respond(self, query: str):
        # Prepend backstory to query to make responses more contextually relevant
        prompt = f"{self.backstory}\nUser: {query}\n{self.name}:"
        return ask_gemini(prompt)

# Create agents with sample queries
if __name__ == "__main__":
    # Instantiate agents
    medical_agent = AI_Agent(
        "Medical Assistant",
        "Assist astronauts with medical issues",
        ["First Aid Guide", "Vitals Monitor"],
        "You are a trained medical assistant designed to help astronauts with medical emergencies in space."
    )

    queries = [
        "How do I treat a burn injury in space?",
        "What is causing the engine malfunction?",
        "Can you guide me to the nearest airlock?"
    ]

    # Output response for each query
    print("Medical Agent Response:")
    for query in queries:
        print(f"Query: {query}")
        print(f"Response: {medical_agent.respond(query)}\n")

if __name__ == "__main__":
    # Instantiate agents
    medical_agent = MedicalAgent()
    tech_support_agent = TechSupportAgent()
    navigation_agent = NavigationAgent()

    # Example queries
    queries = [
        "How do I treat a burn injury in space?",
        "What is causing the engine malfunction?",
        "Can you guide me to the nearest airlock?"
    ]

    # Test responses from each agent
    print("Medical Agent Response:")
    for query in queries:
        print(f"Query: {query}")
        print(f"Response: {medical_agent.respond(query)}\n")

    print("Tech Support Agent Response:")
    for query in queries:
        print(f"Query: {query}")
        print(f"Response: {tech_support_agent.respond(query)}\n")

    print("Navigation Agent Response:")
    for query in queries:
        print(f"Query: {query}")
        print(f"Response: {navigation_agent.respond(query)}\n")

for query in queries:
    response = medical_agent.respond(query)
    print(f"🩺 Medical Agent Response to '{query}':\n➡️ {response}\n")